<?php

namespace comem\NewsroomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{

    public function findAllByTheme($theme)
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb->join('a.themes', 't');
        
        $qb->where('t.ref = :theme')
            ->setParameter('theme', $theme->getRef());
            
        $qb->orderBy('a.grade', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    public function findAllOrder()
    {
        $qb = $this->createQueryBuilder('a');
            
        $qb->orderBy('a.id', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    
    public function search($search)
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb->join('a.themes', 't');

        $searches= explode(' ', $search);

        foreach ($searches as $word) {
            $qb->orWhere("a.title LIKE :search")
                ->setParameter('search', '%'.$word.'%');
            
            $qb->orWhere("a.description LIKE :search")
                ->setParameter('search', '%'.$word.'%');
                
            $qb->orWhere("a.address LIKE :search")
                ->setParameter('search', '%'.$word.'%');
                
            $qb->orWhere("t.title LIKE :search")
                ->setParameter('search', '%'.$word.'%');
                
            $qb->orWhere("t.ref LIKE :search")
                ->setParameter('search', '%'.$word.'%');
        }
        
        $qb->groupBy('a.id');
        
        $qb->orderBy('a.grade', 'DESC');
        
        
        return $qb->getQuery()->getArrayResult();
    }

}
