<?php

namespace comem\NewsroomBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{

    public function findAllByTheme($theme)
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb->where('a.category = :theme')
            ->setParameter('theme', $theme);
            
        
        return $qb->getQuery()->getResult();
    }

}
