comem_newsroom_home:
    pattern:  /
    defaults: { _controller: comemNewsroomBundle:Article:home }
    
comem_newsroom_directory:
    pattern:  /annuaire
    defaults: { _controller: comemNewsroomBundle:Directory:list }
    
comem_newsroom_directory_add:
    pattern:  /annuaire/add
    defaults: { _controller: comemNewsroomBundle:Directory:add }
    
comem_newsroom_directory_edit:
    pattern:  /annuaire/edit/{ad}
    defaults: { _controller: comemNewsroomBundle:Directory:edit }
    
comem_newsroom_theme:
    pattern:  /{theme}
    defaults: { _controller: comemNewsroomBundle:Article:theme }

