comem_newsroom_home:
    pattern:  /
    defaults: { _controller: comemNewsroomBundle:Article:home }
    
comem_newsroom_about:
    pattern:  /a-propos
    defaults: { _controller: comemNewsroomBundle:Article:about }

comem_newsroom_directory_public:
    pattern:  /annuaire
    defaults: { _controller: comemNewsroomBundle:Directory:listPublic }
    
comem_newsroom_directory:
    pattern:  /admin/annuaire
    defaults: { _controller: comemNewsroomBundle:Directory:list }
    
comem_newsroom_directory_json:
    pattern:  /annuaire.json
    defaults: { _controller: comemNewsroomBundle:Directory:search }
    
comem_newsroom_directory_add:
    pattern:  /admin/annuaire/add
    defaults: { _controller: comemNewsroomBundle:Directory:add }
    
comem_newsroom_directory_edit:
    pattern:  /admin/annuaire/edit/{ad}
    defaults: { _controller: comemNewsroomBundle:Directory:edit }
    
comem_newsroom_directory_theme:
    pattern:  /theme
    defaults: { _controller: comemNewsroomBundle:Directory:listTheme }
    
comem_newsroom_directory_theme_add:
    pattern:  /admin/theme/add
    defaults: { _controller: comemNewsroomBundle:Directory:addTheme }
    
comem_newsroom_directory_theme_edit:
    pattern:  /admin/theme/edit/{theme}
    defaults: { _controller: comemNewsroomBundle:Directory:editTheme }
    
comem_newsroom_report:
    pattern:  /report/{title}
    defaults: { _controller: comemNewsroomBundle:Article:report }
    
comem_newsroom_theme:
    pattern:  /{theme}
    defaults: { _controller: comemNewsroomBundle:Article:theme }

